@startuml
title Animal Simulation Use-Case Diagram

actor User

rectangle AnimalSimulationSystem {
    usecase CreateBoard
    usecase CreateAntelope
    usecase CreateZebra
    usecase CreateHyena
    usecase CreateLion
    usecase PlaceAnimal
    usecase MoveAnimal
    usecase UpdateBoard
    usecase PrintBoard
}

User --> CreateBoard
User --> CreateAntelope
User --> CreateZebra
User --> CreateHyena
User --> CreateLion
User --> PlaceAnimal
User --> MoveAnimal
User --> UpdateBoard
User --> PrintBoard

CreateBoard --> PlaceAnimal
CreateAntelope --> PlaceAnimal
CreateZebra --> PlaceAnimal
CreateHyena --> PlaceAnimal
CreateLion --> PlaceAnimal
PlaceAnimal --> UpdateBoard
MoveAnimal --> UpdateBoard
UpdateBoard --> PrintBoard

@enduml